
$Scripts = "\\techshare\Scripts"
."$Scripts\Deploy-Package.ps1"
."$Scripts\Get-PingStatus.ps1"
."$Scripts\Get-BitlockerKey.ps1"
."$Scripts\HBSSTools.ps1"
."$Scripts\Get-ComputerUserInfo.ps1"
."$Scripts\Get-InstalledSoftware.ps1"
."$Scripts\Get-NetworkSettings.ps1"
."$Scripts\Get-Clipboard.ps1"
."$Scripts\Out-ClipboardText.ps1"
."$Scripts\Get-UserWorkstations.ps1"
."$Scripts\Get-WhosLoggedOn.ps1"
."$Scripts\Get-WhatsOnline.ps1"
."$Scripts\SCForceOption.ps1"
."$Scripts\Send-Popup.ps1"